name: Build VoidEditor Fork

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Kerberos dependencies
        run: sudo apt-get update && sudo apt-get install -y libkrb5-dev

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Package
        run: pnpm run dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/**
